
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-organic-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: proj-organic-f23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"allychu-courseTable","number":43,"title":"Added Courses Tables","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/43"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Courses-delete","number":41,"title":"B1.B Backend DELETE operations on Course Controller for Courses, Course Staff","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/41"},{"author":{"id":"MDQ6VXNlcjkwNjczMzc2","is_bot":false,"login":"dayvidwang","name":""},"headRefName":"dayvidwang-Courses-put","number":40,"title":"B1.A Backend PUT operations on Course Controller for Courses, Course Staff","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/40"},{"author":{"id":"U_kgDOB8FKHg","is_bot":false,"login":"shuyiwan","name":"Shuyi Wan"},"headRefName":"Shuyi-toggle-interceptors","number":34,"title":"Toggle Interceptors and Interceptors Test","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/34"},{"author":{"id":"MDQ6VXNlcjU0OTAxOTc3","is_bot":false,"login":"chelseastoner","name":"Chelsea Stoner"},"headRefName":"Chelsea-schools-fixtures","number":33,"title":"#11/F1: Add Schools Fixtures","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/33"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-add-school-entity","number":32,"title":"do - Add School Entity","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/32"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"darylou-add-toggle-buttons","number":18,"title":"do - Add Toggle Admin/Instructor Buttons","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/18"},{"author":{"id":"MDQ6VXNlcjgwMDY1NjAx","is_bot":false,"login":"sumitgupta314","name":"Sumit Gupta"},"headRefName":"sg-GET-course-by-id","number":15,"title":"Added get by id endpoint and test cases","url":"https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-4/pull/15"}]
